// return selected categories
function getCategories() {
    const categories = [];
    document.querySelectorAll('#categories input').forEach(x => {
        if (x.checked) {
            categories.push(x.id);
        }
    });
    return categories;
}

function randomize() {
    const phraseEl = document.querySelector('#phrase');
    const categoryEl = document.querySelector('#category');
    const phrases = [];
    const categories = getCategories();
    // filter phrases by selected categories
    PHRASES.forEach(x => {
        let add = false;
        x.categories.forEach(a => {
            categories.forEach(b => {
                if (a == b) {
                    add = true;
                }
            });
        });
        if (add) {
            phrases.push(x);
        }
    });
    const index = Math.floor(Math.random() * phrases.length);
    const phrase = phrases[index];
    phraseEl.innerText = phrase.phrase;
    categoryEl.innerText = '(category: ' + phrase.categories.join(', ') + ')';
    getCategories();
}

window.onload = () => {
    const randomEl = document.querySelector('#random');
    randomEl.onclick = randomize;
    randomize();
};

const PHRASES = [
    {"phrase": "The Little Mermaid", "categories": ["movie"]},
    {"phrase": "Robin Hood", "categories": ["movie"]},
    {"phrase": "Winnie the Pooh", "categories": ["movie"]},
    {"phrase": "Sleeping Beauty", "categories": ["movie"]},
    {"phrase": "101 Dalmatians", "categories": ["movie"]},
    {"phrase": "Lady & The Tramp", "categories": ["movie"]},
    {"phrase": "The Hunchback of Notre Dame", "categories": ["movie"]},
    {"phrase": "Aladdin", "categories": ["movie"]},
    {"phrase": "Snow White", "categories": ["movie"]},
    {"phrase": "Dumbo", "categories": ["movie"]},
    {"phrase": "Bambi", "categories": ["movie"]},
    {"phrase": "Pinocchio", "categories": ["movie"]},
    {"phrase": "The Jungle Book", "categories": ["movie"]},
    {"phrase": "The Lion King", "categories": ["movie"]},
    {"phrase": "Beauty and the Beast", "categories": ["movie"]},
    {"phrase": "Pocahontas", "categories": ["movie"]},
    {"phrase": "Cinderella", "categories": ["movie"]},
    {"phrase": "Alice in Wonderland", "categories": ["movie"]},
    {"phrase": "Peter Pan", "categories": ["movie"]},
    {"phrase": "Fox and the Hound", "categories": ["movie"]},
    {"phrase": "James Bond", "categories": ["movie"]},
    {"phrase": "Men in Black", "categories": ["movie"]},
    {"phrase": "Star Wars", "categories": ["movie"]},
    {"phrase": "Forest Gump", "categories": ["movie"]},
    {"phrase": "The Sandlot", "categories": ["movie"]},
    {"phrase": "Indiana Jones", "categories": ["movie"]},
    {"phrase": "Willy Wonka", "categories": ["movie"]},
    {"phrase": "Back to the Future", "categories": ["movie"]},
    {"phrase": "The Mighty Ducks", "categories": ["movie"]},
    {"phrase": "The Wizard of Oz", "categories": ["movie"]},
    {"phrase": "The Shining", "categories": ["movie"]},
    {"phrase": "A Clockwork Orange", "categories": ["movie"]},
    {"phrase": "Texas Chainsaw Massacre", "categories": ["movie"]},
    {"phrase": "Toy Story", "categories": ["movie"]},
    {"phrase": "The Terminator", "categories": ["movie"]},
    {"phrase": "Predator", "categories": ["movie"]},
    {"phrase": "Alien", "categories": ["movie"]},
    {"phrase": "Mission Impossible", "categories": ["movie"]},
    {"phrase": "Tomb Raider", "categories": ["movie"]},
    {"phrase": "Ghostbusters", "categories": ["movie"]},
    {"phrase": "The Big Lebowski", "categories": ["movie"]},
    {"phrase": "Titanic", "categories": ["movie"]},
    {"phrase": "Rocky", "categories": ["movie"]},
    {"phrase": "The Blair Witch Project", "categories": ["movie"]},
    {"phrase": "Jaws", "categories": ["movie"]},
    {"phrase": "Halloween", "categories": ["movie"]},
    {"phrase": "The Ring", "categories": ["movie"]},
    {"phrase": "Silence of the Lambs", "categories": ["movie"]},
    {"phrase": "Kill Bill", "categories": ["movie"]},
    {"phrase": "The Sixth Sense", "categories": ["movie"]},
    {"phrase": "A Christmas Story", "categories": ["movie"]},
    {"phrase": "Edward Scissorhands", "categories": ["movie"]},
    {"phrase": "Home Alone", "categories": ["movie"]},
    {"phrase": "Nightmare Before Christmas", "categories": ["movie"]},
    {"phrase": "Pirates of the Caribbean", "categories": ["movie"]},
    {"phrase": "Mrs Doubtfire", "categories": ["movie"]},
    {"phrase": "Saw", "categories": ["movie"]},
    {"phrase": "Twilight", "categories": ["movie"]},
    {"phrase": "The Matrix", "categories": ["movie"]},
    {"phrase": "Fight Club", "categories": ["movie"]},
    {"phrase": "The Wolf of Wall Street", "categories": ["movie"]},
    {"phrase": "Life of Pi", "categories": ["movie"]},
    {"phrase": "Wall-E", "categories": ["movie"]},
    {"phrase": "Pan's Labyrinth", "categories": ["movie"]},
    {"phrase": "The Lord of the Rings", "categories": ["movie"]},
    {"phrase": "Shrek", "categories": ["movie"]},
    {"phrase": "The Truman Show", "categories": ["movie"]},
    {"phrase": "Braveheart", "categories": ["movie"]},
    {"phrase": "Pulp Fiction", "categories": ["movie"]},
    {"phrase": "Jurassic Park", "categories": ["movie"]},
    {"phrase": "Die Hard", "categories": ["movie"]},
    {"phrase": "Scarface", "categories": ["movie"]},
    {"phrase": "E.T.", "categories": ["movie"]},
    {"phrase": "Poltergeist", "categories": ["movie"]},
    {"phrase": "The Goonies", "categories": ["movie"]},
    {"phrase": "Gremlins", "categories": ["movie"]},
    {"phrase": "The Breakfast Club", "categories": ["movie"]},
    {"phrase": "The Princess Bride", "categories": ["movie"]},
    {"phrase": "IT", "categories": ["movie"]},
    {"phrase": "Beetlejuice", "categories": ["movie"]},
    {"phrase": "Caddyshack", "categories": ["movie"]},
    {"phrase": "The NeverEnding Story", "categories": ["movie"]},
    {"phrase": "Nightmare on Elm Street", "categories": ["movie"]},
    {"phrase": "Honey, I Shrunk the Kids", "categories": ["movie"]},
    {"phrase": "Labyrinth", "categories": ["movie"]},
    {"phrase": "Short Circuit", "categories": ["movie"]},
    {"phrase": "Friday the 13th", "categories": ["movie"]},
    {"phrase": "The Land Before Time", "categories": ["movie"]},
    {"phrase": "Something About Mary", "categories": ["movie"]},
    {"phrase": "Tremors", "categories": ["movie"]},
    {"phrase": "Friday", "categories": ["movie"]},
    {"phrase": "Hocus Pocus", "categories": ["movie"]},
    {"phrase": "The Exorcist", "categories": ["movie"]},
    {"phrase": "Carrie", "categories": ["movie"]},
    {"phrase": "The Flintstones", "categories": ["cartoon"]},
    {"phrase": "The Jetsons", "categories": ["cartoon"]},
    {"phrase": "Scooby Doo", "categories": ["cartoon"]},
    {"phrase": "Spider-Man", "categories": ["cartoon"]},
    {"phrase": "Tom and Jerry", "categories": ["cartoon"]},
    {"phrase": "Looney Tunes", "categories": ["cartoon"]},
    {"phrase": "SpongeBobg SquarePants", "categories": ["cartoon"]},
    {"phrase": "DuckTales", "categories": ["cartoon"]},
    {"phrase": "The Simpsons", "categories": ["cartoon"]},
    {"phrase": "Dexter's Laboratory", "categories": ["cartoon"]},
    {"phrase": "Teenage Mutant Ninja Turtles", "categories": ["cartoon"]},
    {"phrase": "Pokemon", "categories": ["cartoon"]},
    {"phrase": "The Pink Panther", "categories": ["cartoon"]},
    {"phrase": "South Park", "categories": ["cartoon"]},
    {"phrase": "Popeye the Sailor", "categories": ["cartoon"]},
    {"phrase": "Pinky and the Brain", "categories": ["cartoon"]},
    {"phrase": "Futurama", "categories": ["cartoon"]},
    {"phrase": "Rugrats", "categories": ["cartoon"]},
    {"phrase": "Batman", "categories": ["cartoon"]},
    {"phrase": "Family Guy", "categories": ["cartoon"]},
    {"phrase": "Hey Arnold!", "categories": ["cartoon"]},
    {"phrase": "The Smurfs", "categories": ["cartoon"]},
    {"phrase": "Inspector Gadget", "categories": ["cartoon"]},
    {"phrase": "King of the Hill", "categories": ["cartoon"]},
    {"phrase": "Ren & Stimpy", "categories": ["cartoon"]},
    {"phrase": "Rocke's Modern Life", "categories": ["cartoon"]},
    {"phrase": "Doug", "categories": ["cartoon"]},
    {"phrase": "Beavis and Butt-head", "categories": ["cartoon"]},
    {"phrase": "angel", "categories": ["easy"]},
    {"phrase": "eyeball", "categories": ["easy"]},
    {"phrase": "pizza", "categories": ["easy"]},
    {"phrase": "angry", "categories": ["easy"]},
    {"phrase": "fireworks", "categories": ["easy"]},
    {"phrase": "pumpkin", "categories": ["easy"]},
    {"phrase": "baby", "categories": ["easy"]},
    {"phrase": "flower", "categories": ["easy"]},
    {"phrase": "beard", "categories": ["easy"]},
    {"phrase": "flying saucer", "categories": ["easy"]},
    {"phrase": "bible", "categories": ["easy"]},
    {"phrase": "giraffe", "categories": ["easy"]},
    {"phrase": "bikini", "categories": ["easy"]},
    {"phrase": "glasses", "categories": ["easy"]},
    {"phrase": "book", "categories": ["easy"]},
    {"phrase": "high heel", "categories": ["easy"]},
    {"phrase": "stairs", "categories": ["easy"]},
    {"phrase": "bucket", "categories": ["easy"]},
    {"phrase": "ice cream cone", "categories": ["easy"]},
    {"phrase": "starfish", "categories": ["easy"]},
    {"phrase": "bumble bee", "categories": ["easy"]},
    {"phrase": "igloo", "categories": ["easy"]},
    {"phrase": "strawberry", "categories": ["easy"]},
    {"phrase": "butterfly", "categories": ["easy"]},
    {"phrase": "lady bug", "categories": ["easy"]},
    {"phrase": "sun", "categories": ["easy"]},
    {"phrase": "lamp", "categories": ["easy"]},
    {"phrase": "tire", "categories": ["easy"]},
    {"phrase": "cat", "categories": ["easy"]},
    {"phrase": "lion", "categories": ["easy"]},
    {"phrase": "church", "categories": ["easy"]},
    {"phrase": "mailbox", "categories": ["easy"]},
    {"phrase": "toothbrush", "categories": ["easy"]},
    {"phrase": "crayon", "categories": ["easy"]},
    {"phrase": "night", "categories": ["easy"]},
    {"phrase": "toothpaste", "categories": ["easy"]},
    {"phrase": "dolphin", "categories": ["easy"]},
    {"phrase": "nose", "categories": ["easy"]},
    {"phrase": "truck", "categories": ["easy"]},
    {"phrase": "egg", "categories": ["easy"]},
    {"phrase": "olympics", "categories": ["easy"]},
    {"phrase": "volleyball", "categories": ["easy"]},
    {"phrase": "eiffel tower", "categories": ["easy"]},
    {"phrase": "cat", "categories": ["easy"]},
    {"phrase": "sun", "categories": ["easy"]},
    {"phrase": "cup", "categories": ["easy"]},
    {"phrase": "ghost", "categories": ["easy"]},
    {"phrase": "flower", "categories": ["easy"]},
    {"phrase": "pie", "categories": ["easy"]},
    {"phrase": "cow", "categories": ["easy"]},
    {"phrase": "banana", "categories": ["easy"]},
    {"phrase": "bug", "categories": ["easy"]},
    {"phrase": "book", "categories": ["easy"]},
    {"phrase": "jar", "categories": ["easy"]},
    {"phrase": "snake", "categories": ["easy"]},
    {"phrase": "tree", "categories": ["easy"]},
    {"phrase": "lips", "categories": ["easy"]},
    {"phrase": "apple", "categories": ["easy"]},
    {"phrase": "slide", "categories": ["easy"]},
    {"phrase": "socks", "categories": ["easy"]},
    {"phrase": "smile", "categories": ["easy"]},
    {"phrase": "coat", "categories": ["easy"]},
    {"phrase": "shoe", "categories": ["easy"]},
    {"phrase": "water", "categories": ["easy"]},
    {"phrase": "heart", "categories": ["easy"]},
    {"phrase": "hat", "categories": ["easy"]},
    {"phrase": "ocean", "categories": ["easy"]},
    {"phrase": "kite", "categories": ["easy"]},
    {"phrase": "dog", "categories": ["easy"]},
    {"phrase": "mouth", "categories": ["easy"]},
    {"phrase": "milk", "categories": ["easy"]},
    {"phrase": "duck", "categories": ["easy"]},
    {"phrase": "eyes", "categories": ["easy"]},
    {"phrase": "skateboard", "categories": ["easy"]},
    {"phrase": "bird", "categories": ["easy"]},
    {"phrase": "boy", "categories": ["easy"]},
    {"phrase": "apple", "categories": ["easy"]},
    {"phrase": "person", "categories": ["easy"]},
    {"phrase": "girl", "categories": ["easy"]},
    {"phrase": "mouse", "categories": ["easy"]},
    {"phrase": "ball", "categories": ["easy"]},
    {"phrase": "house", "categories": ["easy"]},
    {"phrase": "star", "categories": ["easy"]},
    {"phrase": "nose", "categories": ["easy"]},
    {"phrase": "bed", "categories": ["easy"]},
    {"phrase": "whale", "categories": ["easy"]},
    {"phrase": "jacket", "categories": ["easy"]},
    {"phrase": "shirt", "categories": ["easy"]},
    {"phrase": "hippo", "categories": ["easy"]},
    {"phrase": "egg", "categories": ["easy"]},
    {"phrase": "cookie", "categories": ["easy"]},
    {"phrase": "cheese", "categories": ["easy"]},
    {"phrase": "ice cream", "categories": ["easy"]},
    {"phrase": "cone", "categories": ["easy"]},
    {"phrase": "drum", "categories": ["easy"]},
    {"phrase": "circle", "categories": ["easy"]},
    {"phrase": "worm", "categories": ["easy"]},
    {"phrase": "spider web", "categories": ["easy"]},
    {"phrase": "bridge", "categories": ["easy"]},
    {"phrase": "bone", "categories": ["easy"]},
    {"phrase": "grapes", "categories": ["easy"]},
    {"phrase": "bell", "categories": ["easy"]},
    {"phrase": "jellyfish", "categories": ["easy"]},
    {"phrase": "bunny", "categories": ["easy"]},
    {"phrase": "truck", "categories": ["easy"]},
    {"phrase": "grass", "categories": ["easy"]},
    {"phrase": "monkey", "categories": ["easy"]},
    {"phrase": "spider", "categories": ["easy"]},
    {"phrase": "bread", "categories": ["easy"]},
    {"phrase": "ears", "categories": ["easy"]},
    {"phrase": "bowl", "categories": ["easy"]},
    {"phrase": "bracelet", "categories": ["easy"]},
    {"phrase": "alligator", "categories": ["easy"]},
    {"phrase": "bat", "categories": ["easy"]},
    {"phrase": "clock", "categories": ["easy"]},
    {"phrase": "moon", "categories": ["easy"]},
    {"phrase": "doll", "categories": ["easy"]},
    {"phrase": "orange", "categories": ["easy"]},
    {"phrase": "ear", "categories": ["easy"]},
    {"phrase": "basketball", "categories": ["easy"]},
    {"phrase": "bike", "categories": ["easy"]},
    {"phrase": "airplane", "categories": ["easy"]},
    {"phrase": "pen", "categories": ["easy"]},
    {"phrase": "seashell", "categories": ["easy"]},
    {"phrase": "rocket", "categories": ["easy"]},
    {"phrase": "cloud", "categories": ["easy"]},
    {"phrase": "bear", "categories": ["easy"]},
    {"phrase": "corn", "categories": ["easy"]},
    {"phrase": "chicken", "categories": ["easy"]},
    {"phrase": "glasses", "categories": ["easy"]},
    {"phrase": "carrot", "categories": ["easy"]},
    {"phrase": "turtle", "categories": ["easy"]},
    {"phrase": "dinosaur", "categories": ["easy"]},
    {"phrase": "headlamp", "categories": ["easy"]},
    {"phrase": "snowman", "categories": ["easy"]},
    {"phrase": "ant", "categories": ["easy"]},
    {"phrase": "giraffe", "categories": ["easy"]},
    {"phrase": "cupcake", "categories": ["easy"]},
    {"phrase": "chair", "categories": ["easy"]},
    {"phrase": "leaf", "categories": ["easy"]},
    {"phrase": "bunk bed", "categories": ["easy"]},
    {"phrase": "snail", "categories": ["easy"]},
    {"phrase": "baby", "categories": ["easy"]},
    {"phrase": "balloon", "categories": ["easy"]},
    {"phrase": "cherry", "categories": ["easy"]},
    {"phrase": "crab", "categories": ["easy"]},
    {"phrase": "football", "categories": ["easy"]},
    {"phrase": "branch", "categories": ["easy"]},
    {"phrase": "taco", "categories": ["medium"]},
    {"phrase": "abraham lincoln", "categories": ["medium"]},
    {"phrase": "kiss", "categories": ["medium"]},
    {"phrase": "pigtails", "categories": ["medium"]},
    {"phrase": "brain", "categories": ["medium"]},
    {"phrase": "kitten", "categories": ["medium"]},
    {"phrase": "playground", "categories": ["medium"]},
    {"phrase": "bubble bath", "categories": ["medium"]},
    {"phrase": "kiwi", "categories": ["medium"]},
    {"phrase": "pumpkin pie", "categories": ["medium"]},
    {"phrase": "buckle", "categories": ["medium"]},
    {"phrase": "lipstick", "categories": ["medium"]},
    {"phrase": "raindrop", "categories": ["medium"]},
    {"phrase": "bus", "categories": ["medium"]},
    {"phrase": "lobster", "categories": ["medium"]},
    {"phrase": "robot", "categories": ["medium"]},
    {"phrase": "car accident", "categories": ["medium"]},
    {"phrase": "lollipop", "categories": ["medium"]},
    {"phrase": "sand castle", "categories": ["medium"]},
    {"phrase": "castle", "categories": ["medium"]},
    {"phrase": "magnet", "categories": ["medium"]},
    {"phrase": "slipper", "categories": ["medium"]},
    {"phrase": "chain saw", "categories": ["medium"]},
    {"phrase": "megaphone", "categories": ["medium"]},
    {"phrase": "snowball", "categories": ["medium"]},
    {"phrase": "circus tent", "categories": ["medium"]},
    {"phrase": "mermaid", "categories": ["medium"]},
    {"phrase": "sprinkler", "categories": ["medium"]},
    {"phrase": "computer", "categories": ["medium"]},
    {"phrase": "minivan", "categories": ["medium"]},
    {"phrase": "statue of liberty", "categories": ["medium"]},
    {"phrase": "mount rushmore", "categories": ["medium"]},
    {"phrase": "tadpole", "categories": ["medium"]},
    {"phrase": "dragon", "categories": ["medium"]},
    {"phrase": "music", "categories": ["medium"]},
    {"phrase": "teepee", "categories": ["medium"]},
    {"phrase": "dumbbell", "categories": ["medium"]},
    {"phrase": "north pole", "categories": ["medium"]},
    {"phrase": "telescope", "categories": ["medium"]},
    {"phrase": "eel", "categories": ["medium"]},
    {"phrase": "nurse", "categories": ["medium"]},
    {"phrase": "train", "categories": ["medium"]},
    {"phrase": "ferris wheel", "categories": ["medium"]},
    {"phrase": "owl", "categories": ["medium"]},
    {"phrase": "tricycle", "categories": ["medium"]},
    {"phrase": "flag", "categories": ["medium"]},
    {"phrase": "pacifier", "categories": ["medium"]},
    {"phrase": "tutu", "categories": ["medium"]},
    {"phrase": "junk mail", "categories": ["medium"]},
    {"phrase": "piano", "categories": ["medium"]},
    {"phrase": "horse", "categories": ["medium"]},
    {"phrase": "door", "categories": ["medium"]},
    {"phrase": "song", "categories": ["medium"]},
    {"phrase": "trip", "categories": ["medium"]},
    {"phrase": "backbone", "categories": ["medium"]},
    {"phrase": "bomb", "categories": ["medium"]},
    {"phrase": "round", "categories": ["medium"]},
    {"phrase": "treasure", "categories": ["medium"]},
    {"phrase": "garbage", "categories": ["medium"]},
    {"phrase": "park", "categories": ["medium"]},
    {"phrase": "ski", "categories": ["medium"]},
    {"phrase": "state", "categories": ["medium"]},
    {"phrase": "whistle", "categories": ["medium"]},
    {"phrase": "palace", "categories": ["medium"]},
    {"phrase": "baseball", "categories": ["medium"]},
    {"phrase": "coal", "categories": ["medium"]},
    {"phrase": "queen", "categories": ["medium"]},
    {"phrase": "dominoes", "categories": ["medium"]},
    {"phrase": "photograph", "categories": ["medium"]},
    {"phrase": "computer", "categories": ["medium"]},
    {"phrase": "aircraft", "categories": ["medium"]},
    {"phrase": "hot dog", "categories": ["medium"]},
    {"phrase": "salt and pepper", "categories": ["medium"]},
    {"phrase": "key", "categories": ["medium"]},
    {"phrase": "whisk", "categories": ["medium"]},
    {"phrase": "frog", "categories": ["medium"]},
    {"phrase": "lawnmower", "categories": ["medium"]},
    {"phrase": "mattress", "categories": ["medium"]},
    {"phrase": "pinwheel", "categories": ["medium"]},
    {"phrase": "cake", "categories": ["medium"]},
    {"phrase": "circus", "categories": ["medium"]},
    {"phrase": "battery", "categories": ["medium"]},
    {"phrase": "mailman", "categories": ["medium"]},
    {"phrase": "cowboy", "categories": ["medium"]},
    {"phrase": "password", "categories": ["medium"]},
    {"phrase": "bicycle", "categories": ["medium"]},
    {"phrase": "skate", "categories": ["medium"]},
    {"phrase": "electricity", "categories": ["medium"]},
    {"phrase": "lightsaber", "categories": ["medium"]},
    {"phrase": "thief", "categories": ["medium"]},
    {"phrase": "teapot", "categories": ["medium"]},
    {"phrase": "spring", "categories": ["medium"]},
    {"phrase": "nature", "categories": ["medium"]},
    {"phrase": "shallow", "categories": ["medium"]},
    {"phrase": "toast", "categories": ["medium"]},
    {"phrase": "outside", "categories": ["medium"]},
    {"phrase": "america", "categories": ["medium"]},
    {"phrase": "roller blading", "categories": ["medium"]},
    {"phrase": "gingerbread man", "categories": ["medium"]},
    {"phrase": "bowtie", "categories": ["medium"]},
    {"phrase": "light bulb", "categories": ["medium"]},
    {"phrase": "platypus", "categories": ["medium"]},
    {"phrase": "music", "categories": ["medium"]},
    {"phrase": "fist", "categories": ["medium"]},
    {"phrase": "base", "categories": ["medium"]},
    {"phrase": "storm", "categories": ["medium"]},
    {"phrase": "mitten", "categories": ["medium"]},
    {"phrase": "easel", "categories": ["medium"]},
    {"phrase": "nail", "categories": ["medium"]},
    {"phrase": "sheep", "categories": ["medium"]},
    {"phrase": "stoplight", "categories": ["medium"]},
    {"phrase": "coconut", "categories": ["medium"]},
    {"phrase": "hippopotamus", "categories": ["medium"]},
    {"phrase": "ring", "categories": ["medium"]},
    {"phrase": "seesaw", "categories": ["medium"]},
    {"phrase": "plate", "categories": ["medium"]},
    {"phrase": "fishing pole", "categories": ["medium"]},
    {"phrase": "hopscotch", "categories": ["medium"]},
    {"phrase": "bell pepper", "categories": ["medium"]},
    {"phrase": "front porch", "categories": ["medium"]},
    {"phrase": "cheek", "categories": ["medium"]},
    {"phrase": "video camera", "categories": ["medium"]},
    {"phrase": "washing machine", "categories": ["medium"]},
    {"phrase": "telephone", "categories": ["medium"]},
    {"phrase": "silverware", "categories": ["medium"]},
    {"phrase": "barn", "categories": ["medium"]},
    {"phrase": "snowflake", "categories": ["medium"]},
    {"phrase": "bib", "categories": ["medium"]},
    {"phrase": "flashlight", "categories": ["medium"]},
    {"phrase": "popsicle", "categories": ["medium"]},
    {"phrase": "muffin", "categories": ["medium"]},
    {"phrase": "sunflower", "categories": ["medium"]},
    {"phrase": "skirt", "categories": ["medium"]},
    {"phrase": "top hat", "categories": ["medium"]},
    {"phrase": "swimming pool", "categories": ["medium"]},
    {"phrase": "tusk", "categories": ["medium"]},
    {"phrase": "radish", "categories": ["medium"]},
    {"phrase": "peanut", "categories": ["medium"]},
    {"phrase": "spool", "categories": ["medium"]},
    {"phrase": "poodle", "categories": ["medium"]},
    {"phrase": "potato", "categories": ["medium"]},
    {"phrase": "face", "categories": ["medium"]},
    {"phrase": "shark", "categories": ["medium"]},
    {"phrase": "fang", "categories": ["medium"]},
    {"phrase": "snowball", "categories": ["medium"]},
    {"phrase": "waist", "categories": ["medium"]},
    {"phrase": "spoon", "categories": ["medium"]},
    {"phrase": "gate", "categories": ["medium"]},
    {"phrase": "bottle", "categories": ["medium"]},
    {"phrase": "mail", "categories": ["medium"]},
    {"phrase": "sheep", "categories": ["medium"]},
    {"phrase": "lobster", "categories": ["medium"]},
    {"phrase": "ice", "categories": ["medium"]},
    {"phrase": "lawn mower", "categories": ["medium"]},
    {"phrase": "bubble", "categories": ["medium"]},
    {"phrase": "seesaw", "categories": ["medium"]},
    {"phrase": "pencil", "categories": ["medium"]},
    {"phrase": "cheeseburger", "categories": ["medium"]},
    {"phrase": "hopscotch", "categories": ["medium"]},
    {"phrase": "rocking chair", "categories": ["medium"]},
    {"phrase": "corner", "categories": ["medium"]},
    {"phrase": "cheek", "categories": ["medium"]},
    {"phrase": "rolly polly", "categories": ["medium"]},
    {"phrase": "popcorn", "categories": ["medium"]},
    {"phrase": "telephone", "categories": ["medium"]},
    {"phrase": "yo-yo", "categories": ["medium"]},
    {"phrase": "seahorse", "categories": ["medium"]},
    {"phrase": "snowflake", "categories": ["medium"]},
    {"phrase": "spine", "categories": ["medium"]},
    {"phrase": "desk", "categories": ["medium"]},
    {"phrase": "sailboat", "categories": ["medium"]},
    {"phrase": "popsicle", "categories": ["medium"]},
    {"phrase": "brain", "categories": ["medium"]},
    {"phrase": "birthday cake", "categories": ["medium"]},
    {"phrase": "skirt", "categories": ["medium"]},
    {"phrase": "knee", "categories": ["medium"]},
    {"phrase": "pineapple", "categories": ["medium"]},
    {"phrase": "tusk", "categories": ["medium"]},
    {"phrase": "sprinkler", "categories": ["medium"]},
    {"phrase": "money", "categories": ["medium"]},
    {"phrase": "spool", "categories": ["medium"]},
    {"phrase": "lighthouse", "categories": ["medium"]},
    {"phrase": "doormat", "categories": ["medium"]},
    {"phrase": "face", "categories": ["medium"]},
    {"phrase": "flute", "categories": ["medium"]},
    {"phrase": "rug", "categories": ["medium"]},
    {"phrase": "snowball", "categories": ["medium"]},
    {"phrase": "purse", "categories": ["medium"]},
    {"phrase": "owl", "categories": ["medium"]},
    {"phrase": "gate", "categories": ["medium"]},
    {"phrase": "suitcase", "categories": ["medium"]},
    {"phrase": "stomach", "categories": ["medium"]},
    {"phrase": "doghouse", "categories": ["medium"]},
    {"phrase": "pajamas", "categories": ["medium"]},
    {"phrase": "bathroom scale", "categories": ["medium"]},
    {"phrase": "peach", "categories": ["medium"]},
    {"phrase": "newspaper", "categories": ["medium"]},
    {"phrase": "watering can", "categories": ["medium"]},
    {"phrase": "hook", "categories": ["medium"]},
    {"phrase": "school", "categories": ["medium"]},
    {"phrase": "beaver", "categories": ["medium"]},
    {"phrase": "french fries", "categories": ["medium"]},
    {"phrase": "beehive", "categories": ["medium"]},
    {"phrase": "beach", "categories": ["medium"]},
    {"phrase": "artist", "categories": ["medium"]},
    {"phrase": "flagpole", "categories": ["medium"]},
    {"phrase": "camera", "categories": ["medium"]},
    {"phrase": "hair dryer", "categories": ["medium"]},
    {"phrase": "mushroom", "categories": ["medium"]},
    {"phrase": "toe", "categories": ["medium"]},
    {"phrase": "pretzel", "categories": ["medium"]},
    {"phrase": "tv", "categories": ["medium"]},
    {"phrase": "quilt", "categories": ["medium"]},
    {"phrase": "chalk", "categories": ["medium"]},
    {"phrase": "dollar", "categories": ["medium"]},
    {"phrase": "soda", "categories": ["medium"]},
    {"phrase": "chin", "categories": ["medium"]},
    {"phrase": "swing", "categories": ["medium"]},
    {"phrase": "garden", "categories": ["medium"]},
    {"phrase": "ticket", "categories": ["medium"]},
    {"phrase": "boot", "categories": ["medium"]},
    {"phrase": "cello", "categories": ["medium"]},
    {"phrase": "rain", "categories": ["medium"]},
    {"phrase": "clam", "categories": ["medium"]},
    {"phrase": "pelican", "categories": ["medium"]},
    {"phrase": "stingray", "categories": ["medium"]},
    {"phrase": "fur", "categories": ["medium"]},
    {"phrase": "blowfish", "categories": ["medium"]},
    {"phrase": "rainbsailboat", "categories": ["medium"]},
    {"phrase": "popsicle", "categories": ["medium"]},
    {"phrase": "brain", "categories": ["medium"]},
    {"phrase": "birthday cake", "categories": ["medium"]},
    {"phrase": "skirt", "categories": ["medium"]},
    {"phrase": "knee", "categories": ["medium"]},
    {"phrase": "pineapple", "categories": ["medium"]},
    {"phrase": "tusk", "categories": ["medium"]},
    {"phrase": "sprinkler", "categories": ["medium"]},
    {"phrase": "money", "categories": ["medium"]},
    {"phrase": "spool", "categories": ["medium"]},
    {"phrase": "lighthouse", "categories": ["medium"]},
    {"phrase": "doormat", "categories": ["medium"]},
    {"phrase": "face", "categories": ["medium"]},
    {"phrase": "flute", "categories": ["medium"]},
    {"phrase": "rug", "categories": ["medium"]},
    {"phrase": "snowball", "categories": ["medium"]},
    {"phrase": "purse", "categories": ["medium"]},
    {"phrase": "owl", "categories": ["medium"]},
    {"phrase": "gate", "categories": ["medium"]},
    {"phrase": "suitcase", "categories": ["medium"]},
    {"phrase": "stomach", "categories": ["medium"]},
    {"phrase": "doghouse", "categories": ["medium"]},
    {"phrase": "pajamas", "categories": ["medium"]},
    {"phrase": "bathroom scale", "categories": ["medium"]},
    {"phrase": "peach", "categories": ["medium"]},
    {"phrase": "newspaper", "categories": ["medium"]},
    {"phrase": "watering can", "categories": ["medium"]},
    {"phrase": "hook", "categories": ["medium"]},
    {"phrase": "school", "categories": ["medium"]},
    {"phrase": "beaver", "categories": ["medium"]},
    {"phrase": "french fries", "categories": ["medium"]},
    {"phrase": "beehive", "categories": ["medium"]},
    {"phrase": "beach", "categories": ["medium"]},
    {"phrase": "artist", "categories": ["medium"]},
    {"phrase": "flagpole", "categories": ["medium"]},
    {"phrase": "camera", "categories": ["medium"]},
    {"phrase": "hair dryer", "categories": ["medium"]},
    {"phrase": "mushroom", "categories": ["medium"]},
    {"phrase": "toe", "categories": ["medium"]},
    {"phrase": "pretzel", "categories": ["medium"]},
    {"phrase": "tv", "categories": ["medium"]},
    {"phrase": "quilt", "categories": ["medium"]},
    {"phrase": "chalk", "categories": ["medium"]},
    {"phrase": "dollar", "categories": ["medium"]},
    {"phrase": "soda", "categories": ["medium"]},
    {"phrase": "chin", "categories": ["medium"]},
    {"phrase": "swing", "categories": ["medium"]},
    {"phrase": "garden", "categories": ["medium"]},
    {"phrase": "ticket", "categories": ["medium"]},
    {"phrase": "boot", "categories": ["medium"]},
    {"phrase": "cello", "categories": ["medium"]},
    {"phrase": "rain", "categories": ["medium"]},
    {"phrase": "clam", "categories": ["medium"]},
    {"phrase": "pelican", "categories": ["medium"]},
    {"phrase": "stingray", "categories": ["medium"]},
    {"phrase": "fur", "categories": ["medium"]},
    {"phrase": "blowfish", "categories": ["medium"]},
    {"phrase": "rainbow", "categories": ["medium"]},
    {"phrase": "happysailboat", "categories": ["medium"]},
    {"phrase": "popsicle", "categories": ["medium"]},
    {"phrase": "brain", "categories": ["medium"]},
    {"phrase": "birthday cake", "categories": ["medium"]},
    {"phrase": "skirt", "categories": ["medium"]},
    {"phrase": "knee", "categories": ["medium"]},
    {"phrase": "pineapple", "categories": ["medium"]},
    {"phrase": "tusk", "categories": ["medium"]},
    {"phrase": "sprinkler", "categories": ["medium"]},
    {"phrase": "money", "categories": ["medium"]},
    {"phrase": "spool", "categories": ["medium"]},
    {"phrase": "lighthouse", "categories": ["medium"]},
    {"phrase": "doormat", "categories": ["medium"]},
    {"phrase": "face", "categories": ["medium"]},
    {"phrase": "flute", "categories": ["medium"]},
    {"phrase": "rug", "categories": ["medium"]},
    {"phrase": "snowball", "categories": ["medium"]},
    {"phrase": "purse", "categories": ["medium"]},
    {"phrase": "owl", "categories": ["medium"]},
    {"phrase": "gate", "categories": ["medium"]},
    {"phrase": "suitcase", "categories": ["medium"]},
    {"phrase": "stomach", "categories": ["medium"]},
    {"phrase": "doghouse", "categories": ["medium"]},
    {"phrase": "pajamas", "categories": ["medium"]},
    {"phrase": "bathroom scale", "categories": ["medium"]},
    {"phrase": "peach", "categories": ["medium"]},
    {"phrase": "newspaper", "categories": ["medium"]},
    {"phrase": "watering can", "categories": ["medium"]},
    {"phrase": "hook", "categories": ["medium"]},
    {"phrase": "school", "categories": ["medium"]},
    {"phrase": "beaver", "categories": ["medium"]},
    {"phrase": "french fries", "categories": ["medium"]},
    {"phrase": "beehive", "categories": ["medium"]},
    {"phrase": "beach", "categories": ["medium"]},
    {"phrase": "artist", "categories": ["medium"]},
    {"phrase": "flagpole", "categories": ["medium"]},
    {"phrase": "camera", "categories": ["medium"]},
    {"phrase": "hair dryer", "categories": ["medium"]},
    {"phrase": "mushroom", "categories": ["medium"]},
    {"phrase": "toe", "categories": ["medium"]},
    {"phrase": "pretzel", "categories": ["medium"]},
    {"phrase": "tv", "categories": ["medium"]},
    {"phrase": "quilt", "categories": ["medium"]},
    {"phrase": "chalk", "categories": ["medium"]},
    {"phrase": "dollar", "categories": ["medium"]},
    {"phrase": "soda", "categories": ["medium"]},
    {"phrase": "chin", "categories": ["medium"]},
    {"phrase": "swing", "categories": ["medium"]},
    {"phrase": "garden", "categories": ["medium"]},
    {"phrase": "ticket", "categories": ["medium"]},
    {"phrase": "boot", "categories": ["medium"]},
    {"phrase": "cello", "categories": ["medium"]},
    {"phrase": "rain", "categories": ["medium"]},
    {"phrase": "clam", "categories": ["medium"]},
    {"phrase": "pelican", "categories": ["medium"]},
    {"phrase": "stingray", "categories": ["medium"]},
    {"phrase": "fur", "categories": ["medium"]},
    {"phrase": "blowfish", "categories": ["medium"]},
    {"phrase": "rainbow", "categories": ["medium"]},
    {"phrase": "happysailboat", "categories": ["medium"]},
    {"phrase": "popsicle", "categories": ["medium"]},
    {"phrase": "brain", "categories": ["medium"]},
    {"phrase": "birthday cake", "categories": ["medium"]},
    {"phrase": "skirt", "categories": ["medium"]},
    {"phrase": "knee", "categories": ["medium"]},
    {"phrase": "pineapple", "categories": ["medium"]},
    {"phrase": "tusk", "categories": ["medium"]},
    {"phrase": "sprinkler", "categories": ["medium"]},
    {"phrase": "money", "categories": ["medium"]},
    {"phrase": "spool", "categories": ["medium"]},
    {"phrase": "lighthouse", "categories": ["medium"]},
    {"phrase": "doormat", "categories": ["medium"]},
    {"phrase": "face", "categories": ["medium"]},
    {"phrase": "flute", "categories": ["medium"]},
    {"phrase": "rug", "categories": ["medium"]},
    {"phrase": "snowball", "categories": ["medium"]},
    {"phrase": "purse", "categories": ["medium"]},
    {"phrase": "owl", "categories": ["medium"]},
    {"phrase": "gate", "categories": ["medium"]},
    {"phrase": "suitcase", "categories": ["medium"]},
    {"phrase": "stomach", "categories": ["medium"]},
    {"phrase": "doghouse", "categories": ["medium"]},
    {"phrase": "pajamas", "categories": ["medium"]},
    {"phrase": "bathroom scale", "categories": ["medium"]},
    {"phrase": "peach", "categories": ["medium"]},
    {"phrase": "newspaper", "categories": ["medium"]},
    {"phrase": "watering can", "categories": ["medium"]},
    {"phrase": "hook", "categories": ["medium"]},
    {"phrase": "school", "categories": ["medium"]},
    {"phrase": "beaver", "categories": ["medium"]},
    {"phrase": "french fries", "categories": ["medium"]},
    {"phrase": "beehive", "categories": ["medium"]},
    {"phrase": "beach", "categories": ["medium"]},
    {"phrase": "artist", "categories": ["medium"]},
    {"phrase": "flagpole", "categories": ["medium"]},
    {"phrase": "camera", "categories": ["medium"]},
    {"phrase": "hair dryer", "categories": ["medium"]},
    {"phrase": "mushroom", "categories": ["medium"]},
    {"phrase": "toe", "categories": ["medium"]},
    {"phrase": "pretzel", "categories": ["medium"]},
    {"phrase": "tv", "categories": ["medium"]},
    {"phrase": "quilt", "categories": ["medium"]},
    {"phrase": "chalk", "categories": ["medium"]},
    {"phrase": "dollar", "categories": ["medium"]},
    {"phrase": "soda", "categories": ["medium"]},
    {"phrase": "chin", "categories": ["medium"]},
    {"phrase": "swing", "categories": ["medium"]},
    {"phrase": "garden", "categories": ["medium"]},
    {"phrase": "ticket", "categories": ["medium"]},
    {"phrase": "boot", "categories": ["medium"]},
    {"phrase": "cello", "categories": ["medium"]},
    {"phrase": "rain", "categories": ["medium"]},
    {"phrase": "clam", "categories": ["medium"]},
    {"phrase": "pelican", "categories": ["medium"]},
    {"phrase": "stingray", "categories": ["medium"]},
    {"phrase": "fur", "categories": ["medium"]},
    {"phrase": "blowfish", "categories": ["medium"]},
    {"phrase": "rainbow", "categories": ["medium"]},
    {"phrase": "happy", "categories": ["medium"]},
    {"phrase": "attic", "categories": ["hard"]},
    {"phrase": "glue", "categories": ["hard"]},
    {"phrase": "pocket watch", "categories": ["hard"]},
    {"phrase": "back seat", "categories": ["hard"]},
    {"phrase": "highchair", "categories": ["hard"]},
    {"phrase": "rock band", "categories": ["hard"]},
    {"phrase": "birthday", "categories": ["hard"]},
    {"phrase": "hockey", "categories": ["hard"]},
    {"phrase": "sasquatch", "categories": ["hard"]},
    {"phrase": "black hole", "categories": ["hard"]},
    {"phrase": "hotel", "categories": ["hard"]},
    {"phrase": "scrambled eggs", "categories": ["hard"]},
    {"phrase": "blizzard", "categories": ["hard"]},
    {"phrase": "jump rope", "categories": ["hard"]},
    {"phrase": "seat belt", "categories": ["hard"]},
    {"phrase": "burrito", "categories": ["hard"]},
    {"phrase": "koala", "categories": ["hard"]},
    {"phrase": "skip", "categories": ["hard"]},
    {"phrase": "captain", "categories": ["hard"]},
    {"phrase": "leprechaun", "categories": ["hard"]},
    {"phrase": "solar eclipse", "categories": ["hard"]},
    {"phrase": "chandelier", "categories": ["hard"]},
    {"phrase": "light", "categories": ["hard"]},
    {"phrase": "space", "categories": ["hard"]},
    {"phrase": "crib", "categories": ["hard"]},
    {"phrase": "mask", "categories": ["hard"]},
    {"phrase": "stethoscope", "categories": ["hard"]},
    {"phrase": "cruise ship", "categories": ["hard"]},
    {"phrase": "mechanic", "categories": ["hard"]},
    {"phrase": "stork", "categories": ["hard"]},
    {"phrase": "dance", "categories": ["hard"]},
    {"phrase": "mom", "categories": ["hard"]},
    {"phrase": "sunburn", "categories": ["hard"]},
    {"phrase": "deodorant", "categories": ["hard"]},
    {"phrase": "mr potato head", "categories": ["hard"]},
    {"phrase": "thread", "categories": ["hard"]},
    {"phrase": "facebook", "categories": ["hard"]},
    {"phrase": "pantyhose", "categories": ["hard"]},
    {"phrase": "tourist", "categories": ["hard"]},
    {"phrase": "flat", "categories": ["hard"]},
    {"phrase": "paper plate", "categories": ["hard"]},
    {"phrase": "united states", "categories": ["hard"]},
    {"phrase": "frame", "categories": ["hard"]},
    {"phrase": "photo", "categories": ["hard"]},
    {"phrase": "wifi", "categories": ["hard"]},
    {"phrase": "full moon", "categories": ["hard"]},
    {"phrase": "pilgram", "categories": ["hard"]},
    {"phrase": "zombie", "categories": ["hard"]},
    {"phrase": "game", "categories": ["hard"]},
    {"phrase": "pirate", "categories": ["hard"]},
    {"phrase": "baseboards", "categories": ["hard"]},
    {"phrase": "ping pong", "categories": ["hard"]},
    {"phrase": "bonnet", "categories": ["hard"]},
    {"phrase": "mast", "categories": ["hard"]},
    {"phrase": "hut", "categories": ["hard"]},
    {"phrase": "welder", "categories": ["hard"]},
    {"phrase": "dryer sheets", "categories": ["hard"]},
    {"phrase": "sunburn", "categories": ["hard"]},
    {"phrase": "houseboat", "categories": ["hard"]},
    {"phrase": "sleep", "categories": ["hard"]},
    {"phrase": "kneel", "categories": ["hard"]},
    {"phrase": "crust", "categories": ["hard"]},
    {"phrase": "grandpa", "categories": ["hard"]},
    {"phrase": "speakers", "categories": ["hard"]},
    {"phrase": "cheerleader", "categories": ["hard"]},
    {"phrase": "dust bunny", "categories": ["hard"]},
    {"phrase": "salmon", "categories": ["hard"]},
    {"phrase": "cabin", "categories": ["hard"]},
    {"phrase": "handle", "categories": ["hard"]},
    {"phrase": "swamp", "categories": ["hard"]},
    {"phrase": "cruise", "categories": ["hard"]},
    {"phrase": "wedding cake", "categories": ["hard"]},
    {"phrase": "crow's nest", "categories": ["hard"]},
    {"phrase": "macho", "categories": ["hard"]},
    {"phrase": "drain", "categories": ["hard"]},
    {"phrase": "foil", "categories": ["hard"]},
    {"phrase": "orbit", "categories": ["hard"]},
    {"phrase": "dream", "categories": ["hard"]},
    {"phrase": "recycle", "categories": ["hard"]},
    {"phrase": "raft", "categories": ["hard"]},
    {"phrase": "gold", "categories": ["hard"]},
    {"phrase": "plank", "categories": ["hard"]},
    {"phrase": "cliff", "categories": ["hard"]},
    {"phrase": "sweater vest", "categories": ["hard"]},
    {"phrase": "cape", "categories": ["hard"]},
    {"phrase": "safe", "categories": ["hard"]},
    {"phrase": "picnic", "categories": ["hard"]},
    {"phrase": "shrink ray", "categories": ["hard"]},
    {"phrase": "leak", "categories": ["hard"]},
    {"phrase": "boa constrictor", "categories": ["hard"]},
    {"phrase": "deep", "categories": ["hard"]},
    {"phrase": "mold", "categories": ["hard"]},
    {"phrase": "cd", "categories": ["hard"]},
    {"phrase": "tiptoe", "categories": ["hard"]},
    {"phrase": "hurdle", "categories": ["hard"]},
    {"phrase": "knight", "categories": ["hard"]},
    {"phrase": "loveseat", "categories": ["hard"]},
    {"phrase": "cloak", "categories": ["hard"]},
    {"phrase": "bedbug", "categories": ["hard"]},
    {"phrase": "bobsled", "categories": ["hard"]},
    {"phrase": "hot tub", "categories": ["hard"]},
    {"phrase": "firefighter", "categories": ["hard"]},
    {"phrase": "cell phone charger", "categories": ["hard"]},
    {"phrase": "beanstalk", "categories": ["hard"]},
    {"phrase": "nightmare", "categories": ["hard"]},
    {"phrase": "coach", "categories": ["hard"]},
    {"phrase": "moth", "categories": ["hard"]},
    {"phrase": "sneeze", "categories": ["hard"]},
    {"phrase": "wooly mammoth", "categories": ["hard"]},
    {"phrase": "pigpen", "categories": ["hard"]},
    {"phrase": "swarm", "categories": ["hard"]},
    {"phrase": "goblin", "categories": ["hard"]},
    {"phrase": "chef", "categories": ["hard"]},
    {"phrase": "applause", "categories": ["hard"]},
    {"phrase": "wax", "categories": ["hard"]},
    {"phrase": "sheep dog", "categories": ["hard"]},
    {"phrase": "s'mores", "categories": ["hard"]},
    {"phrase": "plow", "categories": ["hard"]},
    {"phrase": "runt", "categories": ["hard"]},
    {"phrase": "half", "categories": ["hard"]},
    {"phrase": "cardboard", "categories": ["hard"]},
    {"phrase": "oar", "categories": ["hard"]},
    {"phrase": "baby-sitter", "categories": ["hard"]},
    {"phrase": "drip", "categories": ["hard"]},
    {"phrase": "shampoo", "categories": ["hard"]},
    {"phrase": "point", "categories": ["hard"]},
    {"phrase": "time machine", "categories": ["hard"]},
    {"phrase": "yardstick", "categories": ["hard"]},
    {"phrase": "think", "categories": ["hard"]},
    {"phrase": "lace", "categories": ["hard"]},
    {"phrase": "darts", "categories": ["hard"]},
    {"phrase": "world", "categories": ["hard"]},
    {"phrase": "avocado", "categories": ["hard"]},
    {"phrase": "bleach", "categories": ["hard"]},
    {"phrase": "shower curtain", "categories": ["hard"]},
    {"phrase": "extension cord", "categories": ["hard"]},
    {"phrase": "dent", "categories": ["hard"]},
    {"phrase": "birthday", "categories": ["hard"]},
    {"phrase": "lap", "categories": ["hard"]},
    {"phrase": "sandbox", "categories": ["hard"]},
    {"phrase": "bruise", "categories": ["hard"]},
    {"phrase": "quicksand", "categories": ["hard"]},
    {"phrase": "fog", "categories": ["hard"]},
    {"phrase": "gasoline", "categories": ["hard"]},
    {"phrase": "pocket", "categories": ["hard"]},
    {"phrase": "honk", "categories": ["hard"]},
    {"phrase": "sponge", "categories": ["hard"]},
    {"phrase": "rim", "categories": ["hard"]},
    {"phrase": "bride", "categories": ["hard"]},
    {"phrase": "wig", "categories": ["hard"]},
    {"phrase": "zipper", "categories": ["hard"]},
    {"phrase": "wag", "categories": ["hard"]},
    {"phrase": "letter opener", "categories": ["hard"]},
    {"phrase": "fiddle", "categories": ["hard"]},
    {"phrase": "water buffalo", "categories": ["hard"]},
    {"phrase": "pilot", "categories": ["hard"]},
    {"phrase": "brand", "categories": ["hard"]},
    {"phrase": "pail", "categories": ["hard"]},
    {"phrase": "baguette", "categories": ["hard"]},
    {"phrase": "rib", "categories": ["hard"]},
    {"phrase": "mascot", "categories": ["hard"]},
    {"phrase": "fireman pole", "categories": ["hard"]},
    {"phrase": "zoo", "categories": ["hard"]},
    {"phrase": "sushi", "categories": ["hard"]},
    {"phrase": "fizz", "categories": ["hard"]},
    {"phrase": "ceiling fan", "categories": ["hard"]},
    {"phrase": "bald", "categories": ["hard"]},
    {"phrase": "banister", "categories": ["hard"]},
    {"phrase": "punk", "categories": ["hard"]},
    {"phrase": "post office", "categories": ["hard"]},
    {"phrase": "season", "categories": ["hard"]},
    {"phrase": "internet", "categories": ["hard"]},
    {"phrase": "chess", "categories": ["hard"]},
    {"phrase": "puppet", "categories": ["hard"]},
    {"phrase": "chime", "categories": ["hard"]},
    {"phrase": "ivy", "categories": ["hard"]},
    {"phrase": "full", "categories": ["hard"]},
    {"phrase": "koala", "categories": ["hard"]},
    {"phrase": "dentist", "categories": ["hard"]}
];